config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "users#home"

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :send_trade_mail
      get :request_trade_mail
    end
  end

  resources :pokemons, only: [:index]
  resources :pokeballs
  resources :requests
  resources :active_pokeballs, only: [] do
    member do
      get :accept_trade
    end
  end
  resources :active_requests, only: [] do
    member do
      get :accept_request
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registations: 'api/v1/registations' }
      resources :users, only: [:show]
      resources :pokemons, only: [:index]
      resources :pokeballs do
        get :search
      end
      resources :requests do
        get :search
      end
    end
  end
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_many :active_pokeballs
  has_many :users, through: :active_pokeballs

  validates :description, presence: true
  validates :level, presence: true
  validates :level, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }

  validates :gender, inclusion: { in: Pokemon::GENDERS }

  validates :hpIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true
  validates :attIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true
  validates :defIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true
  validates :spaIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true
  validates :spdIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true
  validates :speIV, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }, allow_blank: true

  scope :expired, -> { where('created_at < ?', Time.zone.now - 7.days) }
end

app/controllers/api/v1/pokeballs_controller.rb
class Api::V1::PokeballsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    pokeballs = Pokeball.all
    users = User.all
    pokemon = Pokemon.order(id: :asc)
    render json: { pokeballs: pokeballs, users: users, pokemon: pokemon }
  end

  def search
    pokeball = []
    pokemon = Pokemon.where("name ILIKE (?)", "%#{params[:getPoke]}%")
    pokemon.each do |poke|
      monster = Pokeball.where(pokemon_id: poke.id)
      pokeball << monster
    end
    render json: { pokeballs: pokeball.flatten }
  end

  def show
    pokeball = Pokeball.find(params[:id])
    pokeball_owner = pokeball.user
    pokemon = pokeball.pokemon
    active = pokeball.active_pokeballs.find_by(user: current_user)
    render json: { pokemon: pokemon, pokeball: pokeball, owner: pokeball_owner, active: active, user: current_user }
  end

  def new
    pokemon = pokemon_names
    render json: { pokemon: pokemon, user: current_user }
  end

  def create
    passed_pokemon = Pokemon.find_by(name: params[:pokeballs][:pokemon])
    new_pokeball = Pokeball.new(pokeball_params(passed_pokemon))
    if new_pokeball.save
      flash[:success] = "Pokemon succesfully offered!"
      render json: { path: "/pokeballs/#{new_pokeball.id}" }
    else
      pokemon = pokemon_names
      flash[:errors] = new_pokeball.errors.full_messages.join(', ')
      render json: { errors: flash[:errors], pokemon: pokemon }
    end
  end

  def edit
    pokeball = Pokeball.find(params[:id])
    pokemon = pokeball.pokemon
    if pokeball.user != current_user
      flash[:errors] = "You may not edit another user's offer"
      redirect_to root_path
    end
    render json: { pokeball: pokeball, pokemon: pokemon }
  end

  def update
    pokeball = Pokeball.find(params[:id])
    if pokeball.user == current_user
      if pokeball.update(update_params)
        flash[:success] = "Offer successfully updated!"
        render json: { path: "/pokeballs/#{pokeball.id}" }
      else
        flash[:errors] = pokeball.errors.full_messages.join(", ")
        render json: { errors: flash[:errors], pokeball: pokeball, pokemon: pokeball.pokemon }
      end
    end
  end

  def destroy
    pokeball = Pokeball.find(params[:id])
    if pokeball.user == current_user
      if pokeball.destroy
        render json: { path: "/", success: "Offer successfully removed." }
      else
        flash[:errors] = pokeball.errors.full_messages.join(", ")
        render json: { path: "/pokeballs/#{pokeball.id}/edit", errors: flash[:errors] }
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def pokeball_params(arg_pokemon)
    params.require(:pokeballs).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV).merge(pokemon: arg_pokemon, user: current_user)
  end

  def update_params
    params.require(:pokeballs).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV)
  end

  def pokemon_names
    @pokemon = []
    Pokemon.order(id: :asc).each do |pokemon|
      @pokemon << pokemon.name
    end
    @pokemon
  end
end

app/controllers/pokeballs_controller.rb
class PokeballsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pokeballs = Pokeball.all
  end

  def show
    @pokeball = Pokeball.find(params[:id])
    @active = @pokeball.active_pokeballs.find_by(user: current_user)
  end

  def new
    @pokeball = Pokeball.new
    @pokemon = pokemon_names
    respond_to do |format|
      format.html
      format.json do
        render json: @pokemon.to_json
      end
    end
  end

  def create
    passed_pokemon = Pokemon.find_by(name: params[:pokeballs][:pokemon])
    new_pokeball = Pokeball.new(pokeball_params(passed_pokemon))
    if new_pokeball.save
      redirect_to pokeball_path(new_pokeball.id)
      flash[:success] = "Pokemon succesfully offered!"
    else
      @pokemon = pokemon_names
      flash[:errors] = new_pokeball.errors.full_messages.join(", ")
      render action: :new
    end
  end

  def edit
    @pokeball = Pokeball.find(params[:id])

    if @pokeball.user != current_user
      flash[:errors] = "You may not edit another user's offer"
      redirect_to root_path
    end
  end

  def update
    @pokeball = Pokeball.find(params[:id])
    if @pokeball.user == current_user
      if @pokeball.update(update_params)
        flash[:success] = "Offer successfully updated!"
        redirect_to pokeball_path(@pokeball.id)
      else
        flash[:errors] = @pokeball.errors.full_messages.join(", ")
        render action: :edit
      end
    end
  end

  def destroy
    @pokeball = Pokeball.find(params[:id])
    if @pokeball.user == current_user
      if @pokeball.destroy
        flash[:success] = "Offer successfully removed."
        redirect_to root_path
      else
        flash[:errors] = @pokeball.errors.full_messages.join(", ")
        render action: :show
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def pokeball_params(arg_pokemon)
    params.require(:pokeballs).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV).merge(pokemon: arg_pokemon, user: current_user)
  end

  def update_params
    params.require(:pokeballs).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV)
  end

  def pokemon_names
    @_pokenames ||= Pokemon.pluck(:name)
  end
end

app/views/pokeballs/edit.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>Change Your Pokemon Offer</h1>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<%= form_for :pokeballs, method: :put, url: pokeball_path(@pokeball.id) do |f| %>

  <div class="row">
    <div class="text-center columns small-3 small-pokediv">
      <%= image_tag @pokeball.pokemon.sprite, class: "small-poke-sprite" %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-7">
      <%= f.label :description %>
      <%= f.text_area :description, value: @pokeball.description %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :level, class: "inline" %>
      <em>(1-100)</em>
      <%= f.number_field :level, value: @pokeball.level %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :hpIV, "HP IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :hpIV, value: @pokeball.hpIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :attIV, "Att IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :attIV, value: @pokeball.attIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :defIV, "Def IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :defIV, value: @pokeball.defIV %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :spaIV, "SpA IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :spaIV, value: @pokeball.spaIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :spdIV, "SpD IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :spdIV, value: @pokeball.spdIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :speIV, "Spe IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :speIV, value: @pokeball.speIV %>
    </div>
  </div>

  <div class="row button-row">
    <div class="submit columns small-7">
      <%= f.submit "Submit Changes", class: "button" %>
    </div>
  </div>
<% end %>

app/views/pokeballs/index.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>All Current Trade Offers</h1>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<% @pokeballs.each do |pokeball| %>
  <div class="row">
    <div id="offer<%= pokeball.id %>" class="text-center columns small-3 pokediv">
      <h5><%= pokeball.user.username %>'s <%= pokeball.pokemon.name %></h5><hr>
      <%= link_to "#{image_tag pokeball.pokemon.sprite, class: 'poke-sprite'}".html_safe, pokeball_path(pokeball.id), id: "poke-link#{pokeball.id}" %>
    </div>
    <div id="offer-detail<%= pokeball.id %>" class="columns small-8 float-left">
      <h5><strong>Level: </strong><%= pokeball.level ? pokeball.level : "?" %></h5>
      <div class="">
        <%= image_tag "types/#{pokeball.pokemon.typeB}.png" if pokeball.pokemon.typeB %>
        <%= image_tag "types/#{pokeball.pokemon.typeA}.png" %>
      </div>
      <h4 class="inline">IVs:</h4><em> <%= link_to "(What are IVs?)", "http://bulbapedia.bulbagarden.net/wiki/Individual_values", target: "_blank" %></em>
      <div class="row">
        <h5 class="iv columns small-1 float-left"><strong>HP: </strong><%= pokeball.hpIV ? pokeball.hpIV : "?" %></h5>
        <h5 class="iv columns small-1 float-left"><strong>Atk: </strong><%= pokeball.attIV ? pokeball.attIV : "?" %></h5>
        <h5 class="iv columns small-1 float-left"><strong>Def: </strong><%= pokeball.defIV ? pokeball.defIV : "?" %></h5>
        <h5 class="iv columns small-1 float-left"><strong>SpA: </strong><%= pokeball.spaIV ? pokeball.spaIV : "?" %></h5>
        <h5 class="iv columns small-1 float-left"><strong>SpD: </strong><%= pokeball.spdIV ? pokeball.spdIV : "?" %></h5>
        <h5 class="iv columns small-1 float-left"><strong>Spe: </strong><%= pokeball.speIV ? pokeball.speIV : "?" %></h5>
      </div>
      <h5><strong>Description: </strong><%= pokeball.description == "" ? "N/A" : pokeball.description %></h5>
    </div>
  </div>
  <hr>
<% end %>

app/views/pokeballs/new.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>Offer a new Pokemon</h1>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<%= form_for @pokeball, as: :pokeball, validate: true, method: :post, url: pokeballs_path do |f| %>

  <div class="row">
    <div class="columns small-7">
      <%= f.label :pokemon %>
      <%= f.select :pokemon, options_for_select(@pokemon) %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :level, class: "inline" %>
      <em>(1-100)</em>
      <%= f.number_field :level %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :gender, class: "inline" %>
      <%= f.select :gender, options_for_select(Pokemon::GENDERS), prompt: '-- Select a Gender' %>
    </div>
  </div>


  <div class="row">
    <div class="field columns small-7">
      <%= f.label :description, class: 'inline' %>
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :hpIV, "HP IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :hpIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :attIV, "Att IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :attIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :defIV, "Def IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :defIV %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-3 float-left">
      <%= f.label :spaIV, "SpA IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :spaIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :spdIV, "SpD IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :spdIV %>
    </div>

    <div class="field columns small-3 float-left">
      <%= f.label :speIV, "Spe IV", class: "inline" %>
      <em>(0-31)</em>
      <%= f.number_field :speIV %>
    </div>
  </div>

  <div class="row button-row submit-zone">
    <div class="submit columns small-7">
      <%= f.submit "Submit Offer", class: "button" %>
    </div>
  </div>
<% end %>

app/views/pokeballs/show.html.erb
<div class="row page-head">
  <div class="columns small-8">
    <h2><%= @pokeball.user.username %>'s Trade Offer for <%= @pokeball.pokemon.name %></h2>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<div class="row">
  <div id="offer<%= @pokeball.id %>" class="text-center columns small-3 pokediv">
    <h5><%= @pokeball.user.username %>'s <%= @pokeball.pokemon.name %></h5><hr>
    <%= image_tag @pokeball.pokemon.sprite, class: "poke-sprite" %>
  </div>
  <div id="offer-detail<%= @pokeball.id %>" class="columns small-8 float-left">
    <h5><strong>Level: </strong><%= @pokeball.level ? @pokeball.level : "?" %></h5>
    <div class="">
      <%= image_tag "types/#{@pokeball.pokemon.typeB}.png" if @pokeball.pokemon.typeB %>
      <%= image_tag "types/#{@pokeball.pokemon.typeA}.png" %>
    </div>
    <h4 class="inline">IVs:</h4><em> <%= link_to "(What are IVs?)", "http://bulbapedia.bulbagarden.net/wiki/Individual_values", target: "_blank" %></em>
    <div class="row">
      <h5 class="iv columns small-1 float-left"><strong>HP: </strong><%= @pokeball.hpIV ? @pokeball.hpIV : "?" %></h5>
      <h5 class="iv columns small-1 float-left"><strong>Atk: </strong><%= @pokeball.attIV ? @pokeball.attIV : "?" %></h5>
      <h5 class="iv columns small-1 float-left"><strong>Def: </strong><%= @pokeball.defIV ? @pokeball.defIV : "?" %></h5>
      <h5 class="iv columns small-1 float-left"><strong>SpA: </strong><%= @pokeball.spaIV ? @pokeball.spaIV : "?" %></h5>
      <h5 class="iv columns small-1 float-left"><strong>SpD: </strong><%= @pokeball.spdIV ? @pokeball.spdIV : "?" %></h5>
      <h5 class="iv columns small-1 float-left"><strong>Spe: </strong><%= @pokeball.speIV ? @pokeball.speIV : "?" %></h5>
    </div>
    <h5><strong>Description: </strong><%= @pokeball.description == "" ? "N/A" : @pokeball.description %></h5>
  </div>
</div>
<div class="row button-row">
  <div class="columns small-12">
    <% if @pokeball.user == current_user %>
      <%= link_to "Edit Offer", edit_pokeball_path(@pokeball.id), class: "button" %>
      <%= link_to "Delete Offer", pokeball_path(@pokeball.id), method: :delete, class: "button" %>
    <% end %>
    <% if current_user && current_user != @pokeball.user && !@active %>
      <%= link_to "Send Trade Request", send_trade_mail_user_path, class: "button" %>
    <% elsif current_user && current_user == @pokeball.user %>
      <div class="button disabled">You cannot request to trade with yourself.</div>
    <% elsif @active %>
      <div class="button disabled">You have already sent a request</div>
    <% else %>
      <%= link_to "You must be logged in to request a trade", new_user_session_path, class: "button" %>
    <% end %>
  </div>
</div>