config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "users#home"

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :send_trade_mail
      get :request_trade_mail
    end
  end

  resources :pokemons, only: [:index]
  resources :pokeballs
  resources :requests
  resources :active_pokeballs, only: [] do
    member do
      get :accept_trade
    end
  end
  resources :active_requests, only: [] do
    member do
      get :accept_request
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registations: 'api/v1/registations' }
      resources :users, only: [:show]
      resources :pokemons, only: [:index]
      resources :pokeballs do
        get :search
      end
      resources :requests do
        get :search
      end
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_many :active_requests
  has_many :users, through: :active_requests

  validates :description, presence: true

  scope :expired, -> { where('created_at < ?', Time.zone.now - 7.days) }
end

app/controllers/api/v1/requests_controller.rb
class Api::V1::RequestsController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    requests = Request.all
    users = User.all
    pokemon = Pokemon.all
    render json: { requests: requests, users: users, pokemon: pokemon }
  end

  def search
    request = []
    pokemon = Pokemon.where("name ILIKE (?)", "%#{params[:getPoke]}%")
    pokemon.each do |poke|
      monster = Request.where(pokemon_id: poke.id)
      request << monster
    end
    render json: { requests: request.flatten }
  end

  def show
    request = Request.find(params[:id])
    request_owner = request.user
    pokemon = request.pokemon
    active = request.active_requests.find_by(user: current_user)
    render json: { pokemon: pokemon, request: request, owner: request_owner, active: active, user: current_user }
  end

  def new
    pokemon = pokemon_names
    render json: { pokemon: pokemon, user: current_user }
  end

  def create
    passed_pokemon = Pokemon.find_by(name: params[:requests][:pokemon])
    new_request = Request.new(request_params(passed_pokemon))
    if new_request.save
      flash[:success] = "Pokemon succesfully offered!"
      render json: { path: "/requests/#{new_request.id}" }
    else
      pokemon = pokemon_names
      flash[:errors] = new_request.errors.full_messages.join(', ')
      render json: { errors: flash[:errors], pokemon: pokemon }
    end
  end

  def edit
    request = Request.find(params[:id])
    pokemon = request.pokemon
    if request.user != current_user
      flash[:errors] = "You may not edit another user's offer"
      redirect_to root_path
    end
    render json: { request: request, pokemon: pokemon }
  end

  def update
    request = Request.find(params[:id])
    if request.user == current_user
      if request.update(update_params)
        flash[:success] = "Request successfully updated!"
        render json: { path: "/requests/#{request.id}" }
      else
        flash[:errors] = request.errors.full_messages.join(", ")
        render json: { errors: flash[:errors], request: request, pokemon: request.pokemon }
      end
    end
  end

  def destroy
    request = Request.find(params[:id])
    if request.user == current_user
      if request.destroy
        render json: { path: "/", success: "Request successfully removed." }
      else
        flash[:errors] = request.errors.full_messages.join(", ")
        render json: { path: "/requests/#{request.id}/edit", errors: flash[:errors] }
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def request_params(arg_pokemon)
    params.require(:requests).permit(:description).merge(pokemon: arg_pokemon, user: current_user)
  end

  def update_params
    params.require(:requests).permit(:description)
  end

  def pokemon_names
    @pokemon = []
    Pokemon.order(id: :asc).each do |pokemon|
      @pokemon << pokemon.name
    end
    @pokemon
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @requests = Request.all
  end

  def show
    @request = Request.find(params[:id])
    @active = @request.active_requests.find_by(user: current_user)
  end

  def new
    @request = Request.new
    @pokemon = pokemon_names
  end

  def create
    passed_pokemon = Pokemon.find_by(name: params[:requests][:pokemon])
    new_request = Request.new(request_params(passed_pokemon))
    if new_request.save
      redirect_to request_path(new_request.id)
      flash[:success] = "Pokemon succesfully requested!"
    else
      @pokemon = pokemon_names
      flash[:errors] = new_request.errors.full_messages.join(", ")
      render action: :new
    end
  end

  def edit
    @request = Request.find(params[:id])

    if @request.user != current_user
      flash[:errors] = "You may not edit another user's request"
      redirect_to root_path
    end
  end

  def update
    @request = Request.find(params[:id])
    if @request.user == current_user
      if @request.update(update_params)
        flash[:success] = "Request successfully updated!"
        redirect_to request_path(@request.id)
      else
        flash[:errors] = @request.errors.full_messages.join(", ")
        render action: :edit
      end
    end
  end

  def destroy
    @request = Request.find(params[:id])
    if @request.user == current_user
      if @request.destroy
        flash[:success] = "Request successfully removed."
        redirect_to root_path
      else
        flash[:errors] = @request.errors.full_messages.join(", ")
        render action: :show
      end
    else
      render(file: File.join(Rails.root, 'public/403.html'), status: 403, layout: false)
    end
  end

  private

  def request_params(arg_pokemon)
    params.require(:requests).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV).merge(pokemon: arg_pokemon, user: current_user)
  end

  def update_params
    params.require(:requests).permit(:description, :level, :hpIV, :attIV, :defIV, :spaIV, :spdIV, :speIV)
  end

  def pokemon_names
    @pokemon = []
    Pokemon.order(id: :asc).each do |pokemon|
      @pokemon << pokemon.name
    end
    @pokemon
  end
end

app/views/requests/edit.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>Change Your Pokemon Request</h1>
  </div>
</div>

<%= form_for :requests, method: :put, url: request_path(@request.id) do |f| %>

  <div class="row">
    <div class="text-center columns small-3 small-pokediv">
      <%= image_tag @request.pokemon.sprite, class: "small-poke-sprite" %>
    </div>
  </div>

  <div class="row">
    <div class="field columns small-7">
      <%= f.label :description %>
      <%= f.text_area :description, value: @request.description %>
    </div>
  </div>

  <div class="row button-row submit-zone">
    <div class="submit columns small-7">
      <%= f.submit "Submit Changes", class: "button" %>
    </div>
  </div>
<% end %>

app/views/requests/index.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>All Current Trade Requests</h1>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<% @requests.each do |request| %>
  <div class="row">
    <div id="request<%= request.id %>" class="text-center columns small-3 pokediv ">
      <h5><%= request.user.username %>'s<br><%= request.pokemon.name %> Request</h5><hr>
      <%= link_to "#{image_tag request.pokemon.sprite, class: 'poke-sprite'}".html_safe, request_path(request.id), id: "request-poke-link#{request.id}" %>
    </div>
    <br>
    <div id="request-detail<%= request.id %>" class="columns small-8 float-left">
      <div class="">
        <%= image_tag "types/#{request.pokemon.typeB}.png" if request.pokemon.typeB %>
        <%= image_tag "types/#{request.pokemon.typeA}.png" %>
      </div>
      <br>
      <h5><strong>Description: </strong><%= request.description == "" ? "N/A" : request.description %></h5>
    </div>
  </div>
  <hr>
<% end %>

app/views/requests/new.html.erb
<div class="row page-head">
  <div class="columns small-12">
    <h1>Request a new Pokemon</h1>
  </div>
</div>

<div class="row search-bar">
  <div class="columns small-12">

  </div>
</div>

<%= form_for :requests, method: :post, url: requests_path do |f| %>

  <div class="row">
    <div class="columns small-7">
      <%= f.label :pokemon %>
      <%= f.select :pokemon, options_for_select(@pokemon) %>
    </div>
</div>

  <div class="row">
    <div class="field columns small-7">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
  </div>

  <div class="row button-row submit-zone">
    <div class="submit columns small-7">
      <%= f.submit "Submit Request", class: "button" %>
    </div>
  </div>
<% end %>

app/views/requests/show.html.erb
<div class="row">
  <div class="columns small-12 page-head">
    <h2><%= @request.user.username %>'s Trade Request for <%= @request.pokemon.name %></h2>
  </div>
</div>

<div class="row">
  <div id="request<%= @request.id %>" class="text-center columns small-3 small-pokediv">
    <%= image_tag @request.pokemon.sprite, class: "small-poke-sprite" %>
  </div>
  <br>
  <div id="request-detail<%= @request.id %>" class="columns small-8 float-left">
    <div class="">
      <%= image_tag "types/#{@request.pokemon.typeB}.png" if @request.pokemon.typeB %>
      <%= image_tag "types/#{@request.pokemon.typeA}.png" %>
    </div>
    <br>
    <h5><strong>Description: </strong><%= @request.description == "" ? "N/A" : @request.description %></h5>
  </div>
</div>
<div class="row button-row">
  <div class="columns small-12">
    <% if @request.user == current_user %>
      <%= link_to "Edit Request", edit_request_path(@request.id), class: "button" %>
      <%= link_to "Delete Request", request_path(@request.id), method: :delete, class: "button" %>
    <% end %>
    <% if current_user && current_user != @request.user && !@active %>
      <%= link_to "Send Trade Request", request_trade_mail_user_path, class: "button" %>
    <% elsif current_user && current_user == @request.user %>
      <div class="button disabled">You cannot request to trade with yourself.</div>
    <% elsif @active %>
      <div class="button disabled">You have already sent a request</div>
    <% else %>
      <%= link_to "You must be logged in to request a trade", new_user_session_path, class: "button" %>
    <% end %>
  </div>
</div>