config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root "users#home"

  devise_for :users
  resources :users, only: [:show] do
    member do
      get :send_trade_mail
      get :request_trade_mail
    end
  end

  resources :pokemons, only: [:index]
  resources :pokeballs
  resources :requests
  resources :active_pokeballs, only: [] do
    member do
      get :accept_trade
    end
  end
  resources :active_requests, only: [] do
    member do
      get :accept_request
    end
  end

  namespace :api do
    namespace :v1 do
      devise_for :users, controllers: { registations: 'api/v1/registations' }
      resources :users, only: [:show]
      resources :pokemons, only: [:index]
      resources :pokeballs do
        get :search
      end
      resources :requests do
        get :search
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Poke-Connector" %></title>

    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>

  </head>

  <body>

    <div id="app">
      <div class="row nav-bar">
        <div class="columns small-12">
          <%= image_tag 'Logo.png'%>
          <% if current_user %>
            <h5 class="text-right">Signed in as <%= current_user.username %></h4>
            <h5 class="text-right"><%= link_to "My Profile", user_path(current_user.id) %></h4>
            <h5 class="text-right"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></h4>
          <% else %>
            <h5 class="text-right"><%= link_to "Sign Up", new_user_registration_path %></h5>
            <h5 class="text-right"><%= link_to "Log In", new_user_session_path %></h5>
            <h5 class="text-right"><%= link_to "Forgot your password?", new_user_password_path %></h5>
          <% end %>
        </div>
      </div>
      <div class="row home-bar">
        <div class="columns small-12">
          <%= link_to "Home", root_path, class: "button" %>
          <%= link_to "Offer a Pokemon", new_pokeball_path, class: "button" %>
          <%= link_to "Request a Pokemon", new_request_path, class: "button" %>
          <%= link_to "All Open Offers", pokeballs_path, class: "button" %>
          <%= link_to "All Open Requests", requests_path, class: "button" %>
        </div>
      </div>
      <div class="row">
        <div class="columns-12 flash-bar text-center">
          <% if flash[:errors] %>
            <%= flash[:errors] %>
          <% end %>
          <% if flash[:success] %>
            <%= flash[:success] %>
          <% end %>
          <%= notice %>
          <%= alert %>
        </div>
      </div>
    </div>

    <div id="not-app">
      <%= yield %>
    </div>

    <div class="row footer">
      <div class="columns small-8 medium-3 legal">
        © 2016 Pokémon. © 1995–2016 Nintendo/Creatures Inc./GAME FREAK inc. Pokémon, Pokémon character names, Nintendo 3DS, Nintendo DS, Wii, Wii U, and Wiiware are trademarks of Nintendo.
      </div>
    </div>
  </body>
</html>